# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'custom_app' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for custom_app
  pod 'THPDFKit', '~> 0.3.1'
  pod 'Cache'
  pod 'Beethoven'
  pod 'SwiftySound'
  target 'custom_appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'custom_appUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
